language: php

php:
  - 5.6

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database recipes_test;'
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - php -S localhost:8000 public/index.php &
  - sleep 3

script:
  - phpunit
#  - vendor/bin/behat -ptravis -shome_ui
#  - vendor/bin/behat -ptravis -shome_domain